controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_joint_4", "wheel_joint_5", "wheel_joint_6"]
    right_wheel_names: ["wheel_joint_1", "wheel_joint_2", "wheel_joint_3"]
    wheel_separation: 0.5
    wheel_radius: 0.1
    use_stamped_vel: false
