controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drive_controller:
      type: diff_drive_controller/DiffDriveController

    steer_controller:
      type: position_controllers/JointGroupPositionController

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["joint_wheel_4","joint_wheel_5","joint_wheel_6"]
    right_wheel_names: ["joint_wheel_1","joint_wheel_2","joint_wheel_3"]

    wheel_separation: 0.54
    wheel_radius: 0.1125

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true 
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

drive_controller:
  ros__parameters:
    left_wheel_names: ["joint_wheel_4", "joint_wheel_5", "joint_wheel_6"]
    right_wheel_names: ["joint_wheel_1", "joint_wheel_2", "joint_wheel_3"]
    wheel_separation: 0.54
    wheel_radius: 0.1125
    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publisher_qos:
      type: "volatile"
      depth: 10

steer_controller:
  ros__parameters:
    joints:
      - joint_right_front
      - joint_right_back
      - joint_left_front
      - joint_left_back
    interface_name: position
