controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drive_controller:
      type: velocity_controllers/JointGroupVelocityController

    steer_controller:
      type: position_controllers/JointGroupPositionController

drive_controller:
  ros__parameters:
    joints:
      - joint_wheel_1
      - joint_wheel_2
      - joint_wheel_3
      - joint_wheel_4
      - joint_wheel_5
      - joint_wheel_6
    interface_name: velocity

steer_controller:
  ros__parameters:
    joints:
      - joint_rotate_1
      - joint_rotate_2
      - joint_rotate_3
      - joint_rotate_4
      - joint_rotate_5
      - joint_rotate_6
    interface_name: position