### ekf config file ###
ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Hz
    sensor_timeout: 0.1
    two_d_mode: true  # if your robot moves on a plane
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Input topics
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # Covariances
    process_noise_covariance: [0.05, 0, 0, 0, 0, 0,
                               0, 0.05, 0, 0, 0, 0,
                               0, 0, 0.0, 0, 0, 0,
                               0, 0, 0, 0.01, 0, 0,
                               0, 0, 0, 0, 0.01, 0,
                               0, 0, 0, 0, 0, 0.02]

    initial_estimate_covariance: [1e-9, 0, 0, 0, 0, 0,
                                  0, 1e-9, 0, 0, 0, 0,
                                  0, 0, 1e-9, 0, 0, 0,
                                  0, 0, 0, 1e-9, 0, 0,
                                  0, 0, 0, 0, 1e-9, 0,
                                  0, 0, 0, 0, 0, 1e-9]

